Planner_server:
  ros__parameters:
    expected_planner_plugins: ["IPSOPlanner"]

    IPSOPlanner:
      plugin: "nav2_ipso_planner::IPSOPlanner"

      #----- IPSO Parameters -----
      n_particles: 300             # Particle Swarm Optimization (PSO) Planner
      n_inherited: 20             # number of inherited particles (Note: need to be less than number of particles - n_particles)
      pointNum: 5                 # number of position points contanined for each particle
      obs_factor: 1.5             # obstacle factor (geater mean obstacles)
      max_speed: 40.0             # maximum speed each particles
      w_inertial_min: 0.25        # minimum inertial Weight
      w_inertial_max: 0.75        # maximum inertial Weight
      w_social_lower: 1.2         # lower social Weight
      w_social_upper: 2.5         # upper social Weight
      w_cognitive_lower: 1.2      # lower cognitive Weight
      w_cognitive_upper: 2.5      # upper cognitive Weight
      initposmode: 2              # Set the generation mode for the initial position points of the particle swarm
      pub_particles: false        # Whether to publish particles
      ipso_max_iter: 100            # maximum iterations
